server:

  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    source: postgres://root:whwhwhwhwhwhwhwh12321wh@localhost:5432/user_service?sslmode=disable
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    db: 0
    password: "123456"
    dial_timeout: 5s
  other:
    register_limit_everydevice_everyday: 3
    max_failed_login_attempts: 5
    account_lock_duration_minutes: 5

bizfig:
  JWT_SECRET_KEY: test
  JWT_SERVICE_KEY: test
  default_unique_length: 6
  JWT_EXPIRED_HOUR: 1


