server:

  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    source: postgres://root:whwhwhwhwhwhwhwh12321wh@localhost:5432/user_service?sslmode=disable&TimeZone=Asia/Shanghai
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    db: 0
    password: "123456"
    dial_timeout: 5s
  other:
    register_limit_everydevice_everyday: 3 #每个设备每天能注册账号的数量
    max_failed_login_attempts: 5 #登录失败x次锁定 和修改密码时输错密码锁定的次数 两个不共用但是相同
    account_lock_duration_minutes: 5 #锁定的分钟数 同上
    password_modify_lock_duration_minutes: 10 #改密码后不能再次修改的分钟数

bizfig:
  JWT_SECRET_KEY: test #jwt的密钥
  JWT_SERVICE_KEY: test
  default_unique_length: 6 #默认生成的唯一标识长度
  JWT_EXPIRED_HOUR: 72 #账号token过期的时间，单位小时


